import React, { ChangeEvent, useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, Camera, ChevronDown, CircleHelp, Compass, Filter, ImagePlus, MapPin, Mic, Package, Plus, Search, ShieldCheck, SlidersHorizontal, Star, Store, Truck, Upload, UserRound, X } from 'lucide-react';
import { categories, products, stores } from '../data';
import { CartLine, CustomerView as CustomerViewType, Product } from '../types';
import { ProductCard, ProductStripCard, ProductVisual, SparkleLabel } from './ProductCard';

interface CustomerViewProps {
  view: CustomerViewType;
  setView: (view: CustomerViewType) => void;
  query: string;
  setQuery: (query: string) => void;
  category: string;
  setCategory: (category: string) => void;
  wished: string[];
  onWish: (product: Product) => void;
  onAdd: (product: Product) => void;
  onOpen: (product: Product) => void;
  onModal: (kind: 'account' | 'appointment' | 'support' | 'prescription') => void;
  cart: CartLine[];
  onCart: () => void;
  toast: (message: string, tone?: 'success' | 'info' | 'warning') => void;
}

const money = (n: number) => `₹${n.toLocaleString('en-IN')}`;

export const CustomerHeader: React.FC<CustomerViewProps> = ({ view, setView, query, setQuery, onModal, cart, onCart, toast }) => {
  const [uploading, setUploading] = useState(false);
  const [language, setLanguage] = useState<'EN' | 'हि'>('EN');
  const totalItems = cart.reduce((sum, line) => sum + line.quantity, 0);
  const uploadImage = (event: ChangeEvent<HTMLInputElement>) => {
    if (!event.target.files?.[0]) return;
    setUploading(true);
    setTimeout(() => { setUploading(false); setQuery('round frames similar to your photo'); toast('Image matched 4 similar frames', 'success'); }, 700);
  };
  return <>
    <header className="sticky top-0 z-30 bg-base-100/95 backdrop-blur border-b border-base-300">
      <div className="navbar max-w-7xl mx-auto px-4 py-3 gap-4">
        <button className="text-left min-w-max" onClick={() => setView('home')}><div className="font-black tracking-tight text-xl">nayan<span className="text-primary">.</span></div><div className="text-[10px] tracking-[.22em] text-base-content/60 uppercase">optical studio</div></button>
        <div className="hidden md:flex gap-1 ml-4"><button className={`btn btn-sm ${view === 'home' ? 'btn-primary' : 'btn-ghost'}`} onClick={() => setView('home')}>{language === 'EN' ? 'Home' : 'होम'}</button><button className={`btn btn-sm ${view === 'shop' ? 'btn-primary' : 'btn-ghost'}`} onClick={() => setView('shop')}>{language === 'EN' ? 'Shop frames' : 'फ्रेम्स'}</button><button className="btn btn-sm btn-ghost" onClick={() => onModal('appointment')}><CalendarDays size={15} /> {language === 'EN' ? 'Book eye test' : 'नेत्र जांच'}</button><button className={`btn btn-sm ${view === 'stores' ? 'btn-primary' : 'btn-ghost'}`} onClick={() => setView('stores')}><Store size={15} /> {language === 'EN' ? 'Stores' : 'स्टोर'}</button></div>
        <div className="flex-1 max-w-xl mx-auto hidden sm:block"><label className="input input-bordered flex items-center gap-2 w-full"><Search size={17} className="opacity-60" /><input className="grow text-sm" placeholder="Try ‘black round glasses under ₹2000’" value={query} onChange={(e) => setQuery(e.target.value)} /><button className="btn btn-ghost btn-xs" title="Voice search" onClick={() => toast('Listening… try saying a frame style', 'info')}><Mic size={16} /></button><label className="btn btn-ghost btn-xs cursor-pointer" title="Search by image"><ImagePlus size={16} /><input className="hidden" type="file" accept="image/*" onChange={uploadImage} /></label></label>{uploading && <div className="text-xs text-primary mt-1">Matching your image…</div>}</div>
        <div className="flex items-center gap-1 ml-auto"><button className="btn btn-ghost btn-sm hidden lg:flex" onClick={() => setLanguage(language === 'EN' ? 'हि' : 'EN')}>{language === 'EN' ? 'हिंदी' : 'English'}</button><button className="btn btn-ghost btn-circle btn-sm hidden sm:flex" onClick={() => onModal('support')} aria-label="Support"><CircleHelp size={18} /></button><button className="btn btn-ghost btn-circle btn-sm" onClick={() => onModal('account')} aria-label="Account"><UserRound size={18} /></button><button className="btn btn-ghost btn-circle btn-sm indicator" onClick={onCart} aria-label="Cart"><Package size={18} />{totalItems > 0 && <span className="indicator-item badge badge-primary badge-xs">{totalItems}</span>}</button></div>
      </div>
      <div className="sm:hidden px-4 pb-3"><label className="input input-bordered flex items-center gap-2 w-full"><Search size={16} className="opacity-60" /><input className="grow text-sm" placeholder="Search frames, brands…" value={query} onChange={(e) => setQuery(e.target.value)} /></label></div>
    </header>
  </>;
};

export const CustomerView: React.FC<CustomerViewProps> = (props) => {
  const filtered = useMemo(() => {
    const q = props.query.toLowerCase();
    return products.filter((p) => {
      const matchesQuery = !q || [p.name, p.brand, p.shape, p.category, p.colors.join(' '), p.price.toString()].join(' ').toLowerCase().includes(q) || (q.includes('under') && p.price < 2000) || (q.includes('black') && p.colors.some((c) => c.toLowerCase().includes('black')));
      const matchesCategory = props.category === 'All frames' || p.category === props.category || (props.category === 'Blue-light' && p.lens.includes('Blue-cut')) || (props.category === 'Premium' && p.price > 2500);
      return matchesQuery && matchesCategory;
    });
  }, [props.query, props.category]);
  return <div className="min-h-screen bg-base-100"><CustomerHeader {...props} />{props.view === 'home' ? <Home {...props} filtered={filtered} /> : props.view === 'stores' ? <Stores {...props} /> : props.view === 'appointments' ? <AppointmentLanding onModal={props.onModal} /> : <Shop {...props} filtered={filtered} />}</div>;
};

interface ContentProps extends CustomerViewProps { filtered: Product[] }

const Home: React.FC<ContentProps> = ({ ...props }) => <main>
  <section className="max-w-7xl mx-auto px-4 pt-8 pb-6"><div className="rounded-3xl bg-primary text-primary-content overflow-hidden relative"><div className="p-7 md:p-12 max-w-2xl"><span className="badge badge-secondary mb-4">THE MONSOON EDIT · 20% OFF</span><h1 className="text-4xl md:text-6xl font-black leading-[.95] tracking-tight">See life<br />in your best light.</h1><p className="mt-5 text-primary-content/80 max-w-md">Thoughtful frames, precise eye care, and a little more confidence in every view.</p><div className="flex flex-wrap gap-3 mt-7"><button className="btn btn-secondary" onClick={() => { props.setView('shop'); props.setCategory('All frames'); }}>Explore frames <ArrowRight size={17} /></button><button className="btn btn-ghost text-primary-content hover:bg-primary-content/10" onClick={() => props.onModal('appointment')}><CalendarDays size={16} /> Book eye test</button></div></div><div className="hero-frame-art hidden md:block"><ProductVisual product={products[0]} /></div><div className="absolute -right-16 -bottom-20 h-64 w-64 rounded-full border border-primary-content/20" /></div></section>
  <section className="max-w-7xl mx-auto px-4 py-5"><div className="flex items-center justify-between mb-4"><div><p className="text-sm font-semibold">Find your frame</p><p className="text-xs text-base-content/60">Curated for every face and every day</p></div><button className="btn btn-ghost btn-sm" onClick={() => props.setView('shop')}>View all <ArrowRight size={15} /></button></div><div className="flex gap-2 overflow-x-auto pb-2">{categories.map((c, i) => <button key={c} className={`btn btn-sm whitespace-nowrap ${i === 0 ? 'btn-primary' : 'btn-outline'}`} onClick={() => { props.setCategory(c); props.setView('shop'); }}>{c}</button>)}</div></section>
  <section className="max-w-7xl mx-auto px-4 py-8"><SectionHeading eyebrow="Fresh perspective" title="New arrivals" action={() => props.setView('shop')} /><div className="flex gap-3 overflow-x-auto pb-2">{products.slice(1, 6).map((p) => <ProductStripCard key={p.id} product={p} onOpen={props.onOpen} />)}</div></section>
  <section className="max-w-7xl mx-auto px-4 py-8"><div className="flex items-end justify-between mb-5"><div><p className="text-xs uppercase tracking-[.2em] text-primary font-semibold">Made for your face</p><h2 className="text-2xl font-bold">Recommended frames</h2></div><SparkleLabel /></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{products.slice(0, 4).map((p) => <ProductCard key={p.id} product={p} wished={props.wished.includes(p.id)} onWish={props.onWish} onOpen={props.onOpen} onAdd={props.onAdd} />)}</div></section>
  <section className="bg-base-200 border-y border-base-300"><div className="max-w-7xl mx-auto px-4 py-10 grid md:grid-cols-3 gap-4"><PromiseCard icon={<ShieldCheck />} title="Precision, always" text="Every pair is checked by our opticians before it reaches you." /><PromiseCard icon={<Truck />} title="Try at home" text="Free delivery and easy 14-day returns across India." /><PromiseCard icon={<Store />} title="Care, in person" text="Visit a Nayan studio for adjustments and eye tests." /></div></section>
  <section className="max-w-7xl mx-auto px-4 py-10"><div className="flex items-end justify-between mb-5"><div><p className="text-xs uppercase tracking-[.2em] text-primary font-semibold">The community says</p><h2 className="text-2xl font-bold">Kind words, clearly seen.</h2></div><div className="flex items-center gap-1 text-sm"><Star className="fill-warning text-warning" size={16} /> 4.9 from 2,400+ reviews</div></div><div className="grid md:grid-cols-3 gap-3">{[['“The frame finder got my fit exactly right. The delivery felt so considered.”', 'Kavya S. · Bengaluru'], ['“My first pair of progressives, explained patiently and no hard sell.”', 'Suresh R. · Pune'], ['“Beautiful frames at honest prices. The Bandra team is lovely.”', 'Rhea M. · Mumbai']].map(([quote, by]) => <div className="card bg-base-200 border border-base-300" key={by}><div className="card-body p-5"><div className="flex text-warning">{[1, 2, 3, 4, 5].map((i) => <Star key={i} size={14} className="fill-current" />)}</div><p className="mt-3 text-sm leading-relaxed">{quote}</p><p className="text-xs text-base-content/60 mt-2">{by}</p></div></div>)}</div></section>
</main>;

const SectionHeading: React.FC<{ eyebrow: string; title: string; action?: () => void }> = ({ eyebrow, title, action }) => <div className="flex items-end justify-between mb-5"><div><p className="text-xs uppercase tracking-[.2em] text-primary font-semibold">{eyebrow}</p><h2 className="text-2xl font-bold">{title}</h2></div>{action && <button className="btn btn-ghost btn-sm" onClick={action}>See all <ArrowRight size={15} /></button>}</div>;
const PromiseCard: React.FC<{ icon: React.ReactNode; title: string; text: string }> = ({ icon, title, text }) => <div className="flex gap-3 p-4"><div className="p-3 rounded-2xl bg-primary/15 text-primary h-fit">{icon}</div><div><h3 className="font-semibold">{title}</h3><p className="text-sm text-base-content/60 mt-1">{text}</p></div></div>;

const Shop: React.FC<ContentProps> = ({ filtered, ...props }) => <main className="max-w-7xl mx-auto px-4 py-8"><div className="breadcrumbs text-sm text-base-content/60 mb-4"><ul><li><button onClick={() => props.setView('home')}>Home</button></li><li>Shop frames</li></ul></div><div className="flex flex-wrap items-end justify-between gap-3 mb-5"><div><h1 className="text-3xl font-bold">Frames for your point of view</h1><p className="text-sm text-base-content/60 mt-1">{filtered.length} styles · Free delivery over ₹999</p></div><button className="btn btn-outline btn-sm" onClick={() => props.toast('Smart filters are applied from the chips below', 'info')}><SlidersHorizontal size={16} /> Filters <ChevronDown size={15} /></button></div><div className="flex gap-2 overflow-x-auto pb-4">{categories.map((c) => <button key={c} className={`btn btn-sm whitespace-nowrap ${props.category === c ? 'btn-primary' : 'btn-ghost bg-base-200'}`} onClick={() => props.setCategory(c)}>{c}</button>)}</div>{props.query && <div className="alert alert-info mb-5 py-3"><SparkleLabel /><span>Showing matches for “{props.query}”</span><button className="btn btn-ghost btn-xs ml-auto" onClick={() => props.setQuery('')}><X size={14} /></button></div>}{filtered.length ? <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{filtered.map((p) => <ProductCard key={p.id} product={p} wished={props.wished.includes(p.id)} onWish={props.onWish} onOpen={props.onOpen} onAdd={props.onAdd} />)}</div> : <div className="card bg-base-200 p-10 text-center"><Search className="mx-auto opacity-50" /><h2 className="font-bold text-xl mt-3">No exact match yet</h2><p className="text-sm text-base-content/60 mt-1">Try “round”, “black”, or browse all frames.</p><button className="btn btn-primary mt-5" onClick={() => { props.setQuery(''); props.setCategory('All frames'); }}>Clear search</button></div>}</main>;

const Stores: React.FC<Pick<CustomerViewProps, 'onModal' | 'toast'>> = ({ onModal, toast }) => <main className="max-w-7xl mx-auto px-4 py-8"><div className="max-w-2xl"><p className="text-xs uppercase tracking-[.2em] text-primary font-semibold">Come say hello</p><h1 className="text-4xl font-black mt-2">Your nearest Nayan studio.</h1><p className="text-base-content/60 mt-3">Expert adjustments, eye tests, and a calm place to find your frame.</p></div><div className="grid md:grid-cols-3 gap-4 mt-8">{stores.map((store) => <div className="card bg-base-200 border border-base-300" key={store.city}><div className="card-body"><div className="flex justify-between"><div className="p-3 rounded-2xl bg-primary/15 text-primary"><MapPin /></div><span className="badge badge-ghost">{store.distance}</span></div><h2 className="card-title mt-3">{store.city}</h2><p className="text-sm text-base-content/60">{store.address}</p><p className="text-xs mt-3"><span className="font-semibold">Open today</span> · {store.hours}</p><div className="card-actions mt-4"><button className="btn btn-primary btn-sm" onClick={() => toast(`Directions opened for ${store.city}`, 'info')}><Compass size={15} /> Directions</button><button className="btn btn-ghost btn-sm" onClick={() => onModal('appointment')}>Book visit</button></div></div></div>)}</div><div className="card bg-primary text-primary-content mt-8"><div className="card-body md:flex-row items-center justify-between"><div><h2 className="card-title">Need a home eye test?</h2><p className="text-sm text-primary-content/75">Our optician can bring a curated edit to your doorstep in select cities.</p></div><button className="btn btn-secondary" onClick={() => onModal('appointment')}><CalendarDays size={16} /> Check availability</button></div></div></main>;

const AppointmentLanding: React.FC<Pick<CustomerViewProps, 'onModal'>> = ({ onModal }) => <main className="max-w-7xl mx-auto px-4 py-10"><div className="grid md:grid-cols-2 gap-10 items-center"><div><span className="badge badge-secondary">Complimentary with every pair</span><h1 className="text-4xl md:text-5xl font-black mt-4">A clearer day starts with a check-up.</h1><p className="text-base-content/60 mt-4 max-w-lg">Book a 30-minute consultation with a certified optician. Walk in with questions, walk out with clarity.</p><button className="btn btn-primary mt-7" onClick={() => onModal('appointment')}><CalendarDays size={17} /> Choose a time</button></div><div className="card bg-base-200 border border-base-300"><div className="card-body p-7"><div className="flex gap-4 items-start"><div className="p-3 rounded-2xl bg-primary/15 text-primary"><CircleHelp /></div><div><h2 className="font-bold text-lg">What happens in 30 minutes?</h2><ul className="text-sm text-base-content/65 mt-3 space-y-3"><li>• Vision screening and prescription review</li><li>• Frame styling for your face shape</li><li>• Lens guidance without the jargon</li><li>• Digital prescription saved to your account</li></ul></div></div></div></div></div></main>;
